### ISSUE TITLE
500 Error on search when missing search settings

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/TEKDB#176]
Search for 'barnacle' with 'resources' results in 500 error.

Theory: a 'search settings' record has not been stored, and its absence is triggering the error

**Comment by rhodges** [comment]
![image](https://github.com/user-attachments/assets/f36a3f01-2c03-48e4-b732-5cd061383640)

**Comment by pollardld** [comment]
Fixed in version 2.1 https://github.com/Ecotrust/TEKDB/tree/v2.1.
