### ISSUE TITLE
Administrator Workflow [ 4 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/TEKDB#3]
PDF or other visual representation of 1-2 processes an administrator would engage in, such as adding new users or importing a database.

**Comment by pollardld** [comment]
[Admin workflow](https://github.com/Ecotrust/TEKDB/files/800699/admin.pdf)

*All Wireframes*  

1. [Admin workflow](https://github.com/Ecotrust/TEKDB/files/800699/admin.pdf)
2. [User workflow](https://github.com/Ecotrust/TEKDB/files/800697/user.pdf)
3. [Full set](https://github.com/Ecotrust/TEKDB/files/800698/TEK.pdf)

**Comment by pollardld** [comment]
todo:  

- [ ] wireframe for adding new users
- [ ] wireframe for importing a database
