### ISSUE TITLE
Find Command-Line solution to populate database from SQL

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/TEKDB#35]
Likely this will work: http://stackoverflow.com/questions/17666249/how-to-import-an-sql-file-using-the-command-line-in-mysql 

* [ ] Update Django settings.py to use MySQL backend
* [ ] Rebuild Django project on new DB
* [ ] know the following
  * [ ] DB Name (should be in settings)
  * [ ] DB User name (should be in settings)
  * [ ] Location of sql file
* [ ] run `mysql -u [db_username] -p [database_name] < [file_location/file.sql]`

**Comment by rhodges** [comment]
Using Postgres now, but done either way.

**Comment by mitt4git** [comment]
Got it. Thanks
